### ISSUE TITLE
Cannot use object of type Spy\Timeline\ResultBuilder\Pager\KnpPager as array

### ISSUE THREAD

**Issue by Zeichen32** [stephpy/timeline-bundle#105]
If i enable the "DuplicateKey" Filter, i got the following error:

```
FatalErrorException: Error: Cannot use object of type
 Spy\Timeline\ResultBuilder\Pager\KnpPager as array in
\vendor\stephpy\timeline\src\Spy\Timeline\Filter\DuplicateKey.php line 46
```

My current configuration looks like this:

``` yml
knp_paginator: ~

spy_timeline:
    paginator: spy_timeline.paginator.knp
    drivers:
        odm:
            object_manager: doctrine.odm.mongodb.document_manager
            classes:
                timeline:  MyBundle\TimelineBundle\Document\Timeline
                action:    MyBundle\TimelineBundle\Document\Action
                component: MyBundle\TimelineBundle\Document\Component
                action_component: MyBundle\TimelineBundle\Document\ActionComponent
    filters:
        duplicate_key:
            priority: 10

        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    true
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
                - spy_timeline.filter.data_hydrator.locator.doctrine_odm
```

Is this a bug or has somebody the same problems with the "DuplicateKey" filter?
