### ISSUE TITLE
[2.0] Pagination

### ISSUE THREAD

**Issue by brentc** [stephpy/timeline-bundle#37]
Noticing that 1.0 doesn't support actual timeline pagination. `TimelinePagerToken::SERVICE_TIMELINE` actually makes a call to `manager->getWall(…)`. Looked into how Pagination is implemented and came up with a suggestion for more flexible support of pagination in 2.0.

`config,yml`:

``` yaml
highco_timeline:
    # …
    paginator: ~ # or highco.timeline.paginator.knp or user provided
    # ....
```

Configuration processing would dynamically add 'setPaginator' calls to specific managers (actions & timelines). Redis managers would then provide their subscribers. OD/RM providers don't need subscribers since knp supports DQL/Builder objects.

Content returning methods would add support for a 'paginate => true' option, and would return the output from AbtractPaginator::paginate()

Thoughts?
