### ISSUE TITLE
[2.0] One manager  ?

### ISSUE THREAD

**Issue by stephpy** [stephpy/timeline-bundle#56]
Hi,

At this moment, we have two managers: `timeline_manager` and `action_manager` which allow user to use different driver for each one.

```
timeline_manager: orm # or redis, odm, propel.
action_manager: orm # or redis, odm, propel.
```

@brentc talked about regroup them, i think that could be a good idea. 

_Benefits_
- Clearer
- Easier to install bundle
- Managers working together with a different driver could be difficult ... (ex, tm => orm and am => redis)

_Cons_
- All datas will be stored on same driver
- May performance could be impacted (in this case, choose only redis driver :D )

If we're OK to have only one manager, i see configuration like that:

``` yml
spy_timeline:
    # one of theses drivers definition
    drivers:
        orm:
            object_manager: ~   # doctrine.orm.entity_manager
            classes:
                timeline_manager: 'Spy\TimelineBundle\Driver\ORM\TimelineManager'
                timeline: 'Acme\YourBundle\Entity\Timeline'
                action: 'Acme\YourBundle\Entity\Action'
                component:'Acme\YourBundle\Entity\Component'
                action_component: 'Acme\YourBundle\Entity\ActionComponent'
        odm:
            object_manager: ~   # doctrine.odm.entity_manager
            classes:
                timeline_manager: 'Spy\TimelineBundle\Driver\ODM\TimelineManager'
                timeline: 'Acme\YourBundle\Document\Timeline'
                action: 'Acme\YourBundle\Document\Action'
                component: 'Acme\YourBundle\Document\Component'
                action_component: 'Acme\YourBundle\Document\ActionComponent'
        redis:
            client: ~ # snc_redis.default
            timeline_key_prefix: timeline:
            action_key_prefix: timeline:action
            pipeline: true
            classes:
                timeline_manager: 'Spy\TimelineBundle\Driver\Redis\TimelineManager'

    # or this
    timeline_manager:  my_own_service
```

Any thoughts ?
