### ISSUE TITLE
DataHydrator with Redis driver

### ISSUE THREAD

**Issue by cbeyer** [stephpy/timeline-bundle#78]
Hello,
I want to use the DataHydrator filter (with ORM). I use the Redis driver in my configuration. I tried the following, but it doesn't work : 

``` yml
spy_timeline:
    drivers:
        redis:
            client:            snc_redis.default
    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    true
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
```

What is wrong ?
