### ISSUE TITLE
Demo not working, what am i doing wrong ?

### ISSUE THREAD

**Issue by tristanbes** [stephpy/timeline-bundle#84]
Hey,

I tryed to use the example with Redis driver,

To sum up i did (i did not paste all the code), 

```
    $subject       = $actionManager->findOrCreateComponent('\User', 2);
    $action        = $actionManager->create($subject, 'control', array('directComplement' => 'the world'));
```

On the spread i send the event to the user 1,

Then I retrieve his wall : 

```
    $subject         = $actionManager->findOrCreateComponent('\User', 1);
```

Finally I render his wall which only contains
" - "

When a do a var_dump I end up with : 

![bug](https://f.cloud.github.com/assets/346010/101208/fb4ead66-68af-11e2-9171-b0497111d750.png)

My config looks like :

``` yml
spy_timeline:
    drivers:
        redis:
            client:           snc_redis.default # snc_redis.default
            pipeline:         true
            prefix:           vlr_timeline
            classes:
                action:           'Spy\Timeline\Model\Action'
                component:        'Spy\Timeline\Model\Component'
                action_component: 'Spy\Timeline\Model\ActionComponent'
    paginator: spy_timeline.paginator.knp
```

What did i do wrong ? I saw that redis must be in immediate delivery, but i can't find that option under snc_redis bundle

thanks
